var Mock = require('mockjs');
var data = function () {
    return Mock.mock({
       "isSuccess":true,
        "questionnaires":{
            "questionnaireId":4,
            "questionnaireDescription":"问卷描述7",
            "questionnaireName":"问卷名称7",
            "problems":[
                {
                    "problemId":1,
                    "problemType":1,
                    "problemContent":"请问您对xx社区卫生服务中心满意吗",
                    "problemRemark":"",
                    "creator":"米喜",
                    "creatTime":1474963113000,
                    "updateTime":1474963113000,
                    "whetherBeUsed":1,
                    "isEnable":1,
                    "options":[
                        {
                            "optionId":1,
                            "problemId":1,
                            "optionContent":"是",
                            "optionRemark":"",
                            "optionOrder":1,
                            "isEnable":1
                        },
                        {
                            "optionId":2,
                            "problemId":1,
                            "optionContent":"否 ",
                            "optionRemark":"",
                            "optionOrder":2,
                            "isEnable":1
                        }
                    ]
                },
                {
                    "problemId":2,
                    "problemType":2,
                    "problemContent":"请问您是xx街道xx居委会",
                    "problemRemark":"",
                    "creator":"米喜",
                    "creatTime":1474963113000,
                    "updateTime":1474963113000,
                    "whetherBeUsed":1,
                    "isEnable":1,
                    "options":[
                        {
                            "optionId":3,
                            "problemId":2,
                            "optionContent":"爱你",
                            "optionRemark":"",
                            "optionOrder":1,
                            "isEnable":1
                        },
                        {
                            "optionId":4,
                            "problemId":2,
                            "optionContent":"恨你",
                            "optionRemark":"",
                            "optionOrder":2,
                            "isEnable":1
                        }
                    ]
                } ,
                {
                    "problemId":3,
                    "problemType":2,
                    "problemContent":"请问您有健康问题是否会优先选择家庭医生呢：",
                    "problemRemark":"",
                    "creator":"米喜",
                    "creatTime":1474963113000,
                    "updateTime":1474963113000,
                    "whetherBeUsed":1,
                    "isEnable":1,
                    "options":[
                        {
                            "optionId":5,
                            "problemId":3,
                            "optionContent":"是",
                            "optionRemark":"",
                            "optionOrder":1,
                            "isEnable":1
                        },
                        {
                            "optionId":6,
                            "problemId":3,
                            "optionContent":"fou",
                            "optionRemark":"",
                            "optionOrder":2,
                            "isEnable":1
                        }
                    ]
                },
                {
                    "problemId":4,
                    "problemType":1,
                    "problemContent":"请问您签约医生是xx街道社区",
                    "problemRemark":"",
                    "creator":"米喜",
                    "creatTime":1474963113000,
                    "updateTime":1474963113000,
                    "whetherBeUsed":1,
                    "isEnable":1,
                    "options":[
                        {
                            "optionId":7,
                            "problemId":4,
                            "optionContent":"满意",
                            "optionRemark":"",
                            "optionOrder":1,
                            "isEnable":1
                        },
                        {
                            "optionId":8,
                            "problemId":4,
                            "optionContent":"不满意",
                            "optionRemark":"",
                            "optionOrder":2,
                            "isEnable":1
                        }
                    ]
                }                   
            ]
        }
    })
}
module.exports = data;